### ISSUE TITLE
Modifica dell'Appointment Content

### ISSUE THREAD

**Issue by msalvati1997** [CSW-Teams/MS3#121]
L'Appointment content deve mostrare i medici partecipanti al turno (SOLO COGNOME). 

Il turno avrà specificato SERVIZIO-MANSIONE (title)

**Comment by Torkin1** [comment]
Ogni assegnazione di turno mostra i cognomi degli utenti allocati.
Se il turno è una GUARDIA, mostra anche gli utenti reperibili.
Questo vale sia per il sommario del turno `Appointment` che per i suoi dettagli `Tooltip`
