### ISSUE TITLE
Fix bux Holidays

### ISSUE THREAD

**Issue by msalvati1997** [CSW-Teams/MS3#148]
A seguito dei problemi riscontrati bisogna sistemare e integrare l'API inserita dal commit fcab574b4b241fa99ea95963dc980b4479da9f3b . 
L'API non è integrata con il resto del sistema e non permette il funzionamento di tutto il resto del sistema.

**Comment by lucaFiscariello** [comment]
I problemi riscontrati sono:

- il metodo getHolidays() in HolidayRestEndpoint non ha i path param conformi con il nome delle variabili del metodo. Ad esempio il path della richiesta è: "/year={currentYear}/country={currentCountry}" allora i nomi dei parametri del metodo devono essere currentYear e currentCountry.
- Calendar setting deve resettare i path param ogni volta che viene soddisfatta una richiesta rest. Altrimenti se viene invocata due volte la funzione getHolidays() di HolidayRestEndpoint si verrà a creare il path https://date.nager.at/api/v3/publicholidays/2023/IT/2023/IT invece di  https://date.nager.at/api/v3/publicholidays/2023/IT
- il metodo getHolidays in CalendarServiceManager deve creare un'istanza di Holiday utilizzando l'epoch day della festività e non i millisecondi.
- il metodo getHolidays() in HolidayRestEndpoint deve restituire anche le domeniche come festività.
- Lato frontend bisogna modificare la chiamata all'API con path corretto.
