### ISSUE TITLE
Desiderata

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#167]
Detta anche preferenza.
Sono i giorni in cui un medico non vorrebbe lavorare, ma se è costretto ci va.

**Comment by msalvati1997** [comment]
- Quando esprimere le desiderate : entro il 10 del mese precedente 
- Limite desiderate 7 giorni al mese (con al massimo 2 week end di desiderata al mese che pesano di più)
- Desiderata può essere :  tutta la giornata (no guardia pomeridiana, no guardia notturna), no guardia giorno , no guardia notte (raffinare le possibilità di scelta)
- Una vacanza desiderata ha un peso:  es compleanno e week end 


- Ferie : non più di due settimane consecutive (30 giorni di ferie per tutti all'anno escluse le domeniche)

**Comment by Torkin1** [comment]
Si dice "I" desiderata.
