### ISSUE TITLE
Tirarsi indietro da una assegnazione turno

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#168]
Come utente vorrei tirarmi indietro da un'assegnazione turno perché ad esempio starò in malattia.

Il sistema dele potermi trovare un sostituto da allocare al posto mio.

**Comment by lucaFiscariello** [comment]
Quando un utente inserisce la malattia , in automatico il server dovrà modificare la schedulazione esistente. Dovrà eliminare l'utente da tutte le assegnazioni turni che coincidono con i giorni di malattia. Successivamente dovrà trovare altri sostituti. I sostituti possono essere sia gli utenti di "riserva" già memorizzati nell'assegnazione turno oppure altri utenti che però devono rispettare tutti i vincoli.

**Comment by massimostanzione** [comment]
Chiuso in quanto duplicato di #318.
