### ISSUE TITLE
Alcune politiche di inclusione/esclusione delle categorie devono essere rispettate anche se il vincolo non stringente corrispondente è violato

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#171]
donne incinta, over62 non possono fare turni faticosi **MAI**, quindi non possono essere vincoli non stringenti

**Comment by lucaFiscariello** [comment]
Attualmente il vicolo che verifica se una  categoria che è associabile ad un particolare turno è un vincolo non stringente, questo vuol dire che può essere forzato. Tuttavia questa forzatura potrebbe far in modo che un utente over62 o incinta possa essere associato ad un turno notturno. Per risolvere il problema NON è possibile rendere il vincolo non stringente altrimenti la forzatura dei vincoli diventerebbe inutile dato che il vincolo che verifica le categorie gestisce moltissime funzionalità del sistema.

**Comment by sebastianopriscan** [comment]
Il concetto di politica non esiste più, pertano tale issue sarà chiusa
