### ISSUE TITLE
Invio feedback utente al completamento di una storia

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#191]
Come utente vorrei poter inviare un feedback relativo a una storia che ho appena completato per far sapere ai devs cosa mi è piaciuto e cosa cambiare.

**Comment by lucaFiscariello** [comment]
In ogni schermata dell'applicazione deve essere presente un bottone che una volta cliccato apre una nuova schermata. In questa nuova schermata l'utente può inserire un suo feedback. Queste informazioni devono poi essere memorizzate nel database.

**Comment by Stack-1** [comment]
Issue chiuso in quanto non si riesce a comprendere bene cosa si intenda con il termine "storia". In particolare, la semantica suggerisce di specificare meglio la user story #190 con dettagli di basso livello di cui l'utente non ha la minima conoscenza.
