### ISSUE TITLE
Cambiare vista dell'applicazione in base al campo attore dell'utente

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#200]
Serve a distinguere la responsabilità dell'utente nel sistema.
Può essere Configuratore, Pianificatore, Utente.

**Comment by Torkin1** [comment]
L'UI deve mostrare solo i casi d'uso accessibili in funzione dell'attore loggato.

**Comment by federicavil** [comment]
Utente: pianificazione globale (senza assegnazione turno manuale), pianificazione singola, turni non modificabili da pianificazione globale, profilo utente, desiderate utente

Pianificatore: genera pianificazione, assegnazione turno manuale, modifica turni, cancellazione turni + schermate utente

Configuratore: schermata modifica parametri vincoli
