### ISSUE TITLE
Ritiro dal turno

### ISSUE THREAD

**Issue by Stack-1** [CSW-Teams/MS3#318]
Come utente vorrei potermi ritirare dal turno per motivi comprovabili. (Es. Malattia, ecc...)

Branch di riferimento per il lavoro svolto per questa issue: https://github.com/CSW-Teams/MS3/tree/issue-318

**Comment by massimostanzione** [comment]
### Spostamento nel backlog
A valle dello _Sprint_ 2 si è deciso di spostare questa _user story_ nel backlog.

Ulteriori suggerimenti per futuri sviluppi:
- schermata storico richieste di ritiro, sia per singoli utenti che globale per il _Pianificatore_
- aggiungere possibilità di poter caricare un file (facoltativo), e.g. certificati medici da caricare entro 3 giorni per giustificazione in caso di malattia
