### ISSUE TITLE
Filtro turni globali per collega

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#38]
Come utente voglio filtrare i turni globali per uno o più nomi di colleghi che partecipano

**Comment by lucaFiscariello** [comment]
Test Accettazione

- Un utente loggato deve poter  visualizzare i turni assegnati a UNO specifico utente
- Un utente loggato deve poter  visualizzare i turni assegnati a due o più utenti di interesse
- La scelta degli utenti di cui si vogliono visualizzare i turni può avvenire scrivendo il nome dell'utente di interesse nell'apposito campo di ricerca
