### ISSUE TITLE
Inserisci turno assegnato

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#41]
Come pianificatore vorrei aggiungere un turno assegnato manualmente alla pianificazione così da apportare velocemente modifiche a una pianificazione già generata.

**Comment by Torkin1** [comment]
Devo poter aggiungere:
- Data
- utenti reperibili
- utenti di guardia 
- servizio

**Comment by Torkin1** [comment]
Data -> calendario in cui si può selezionare il giorno del mese
turno -> tendina che sceglie il servizio, che abilita tendina dei turni registrati per quel servizio
utenti di guardia/reperibili -> tendina scrollabile con campo scrivibile che filtra per nome.

**Comment by Torkin1** [comment]
Pianificatore inizia storia cliccando su un bottone "inserisci turno" nella vista dello scheduling globale

**Comment by lucaFiscariello** [comment]
Test Accettazione

- Non è possibile associare un turno a degli utenti  se tra gli utenti di guardia e quelli reperibili compare lo stesso medico.
- Se gli utenti di guardia e gli utenti reperibili sono tutti diversi tra loro, allora è possibile creare un associazione turno.
