### ISSUE TITLE
Consulta lista utenti scambiabili

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#42]
Come utente vorrei consultare una lista di turni scambiabili con il mio così da poter sapere con chi posso scambiarmi

**Comment by lucaFiscariello** [comment]
La lista degli utenti scambiali è la lista degli utenti che possono essere associati ad una particolare assegnazione turno senza rompere nessun vincolo. L'idea è che quando un utente vuole visualizzare gli utenti a cui chiedere uno scambio turno si avvia il seguente flusso:

- L'utente  selezione l'assegnazione turno da scambiare
- Il frontend contatta il backend passandogli l'assegnazione turno selezionata dall'utente
- Il backend tramite un algoritmo verifica quali utenti possono essere associati a quella assegnazione turno senza rompere nessun vincolo
- Il backend restituisce la lista degli utenti al frontend
