### ISSUE TITLE
Problema di orario sull'interfaccia grafica

### ISSUE THREAD

**Issue by Fanfarillo** [CSW-Teams/MS3#482]
In breve: durante l'ora solare, sull'interfaccia gli orari risultano shiftati in avanti di 1 ora. Durante l'ora legale, invece, risultano shiftati in avanti di 2 ore.

**Comment by DaniloDamico** [comment]
questo è il comportamento previsto dai requisiti discussi in classe: gmt nel backend e timezone locale nel frontend
