### ISSUE TITLE
Modifica servizio non viene salvata

### ISSUE THREAD

**Issue by Stack-1** [CSW-Teams/MS3#536]
Bug riguardante la funzionalità di modifica di un servizio da parte del configuratore. Infatti anche se il frontend viene aggiornato correttamente, non viene invece propagato correttamente il cambiamento in persistenza.
Infatti, ricariccando la pagina si ottiene nuovamente il vecchio servizio.

**Comment by massimostanzione** [comment]
Chiuso in quanto duplicato di #530
