### ISSUE TITLE
Sistemare il footer in "gestione festività", "calendario" e "scambio turni"

### ISSUE THREAD

**Issue by Ralisin** [CSW-Teams/MS3#581]
Nella pagina di "gestione festività" e in "calendario" il footer sta in mezzo allo schermo

**Comment by AlessandroFinocchi** [comment]
Still have to solve issue on "Gestione Festività" Configurator page

**Comment by AlessandroFinocchi** [comment]
Vedi [pagina](https://github.com/DesignRevision/shards-dashboard-react/tree/master/src) per vedere come hanno fatto il footer negli anni passati
