### ISSUE TITLE
Richiesta scambio turno

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#6]
Come utente voglio poter richedere un cambio turno con un altro utente cosi che possiamo risolvere imprevisti

**Comment by federicavil** [comment]
Come utente voglio poter informare il pianificatore e l'utente con cui voglio effettuare lo scambio della mia richiesta di scambio così da poter ottenere un'accettazione della mia richiesta

**Comment by lucaFiscariello** [comment]
Lo scambio turno deve essere implementato prevedendo l'interazione tra due utenti. Attualmente è possibile realizzare uno scambio turno ma senza interazione. Il flusso della storia dovrebbe essere il seguente:

- Un utente chiede uno scambio turno attraverso la funzionalità già offerta dal software attualmente
- La richiesta di scambio turno può essere inviata in broadcast a tutti o a un utente specifico
- Tutti gli utenti, o l'utente a cui è arrivata la richiesta di scambio turno, ricevono la notifica di una richiesta di scambio
- L'utente che riceve la richiesta di scambio può decidere se accettare o rifiutare la richiesta
- L'utente che ha inviato inizialmente la richiesta riceve una risposta
- Solo se la richiesta di scambio turno è accettata allora verrà aggiornato l'assegnazione turno nella schedulazione.

Sarebbe opportune prevedere una nuova classe "Richiesta". Questa entità memorizza chi ha effettuato la richiesta, a chi è rivolta a quale assegnazione turno si riferisce.
