### ISSUE TITLE
Inserimento Festività

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#73]
Come configuratore vorrei poter inserire le festività nel sistema così che si possa sapere quando un utente è assegnato a un turno in un giorno festivo

**Comment by sebastianopriscan** [comment]
La pull request aperta permette di inserire nuovi eventi, ma non di cancellarli, tale funzionalità rimane ancora da implementare, bisogna decidere se inserirla in una nuova storia o meno
