### ISSUE TITLE
Inserimento Servizi

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#74]
Come configuratore vorrei inserire i servizi e le tipologie di turno associate a ciascuno di loro

**Comment by massimostanzione** [comment]
Tasks:

- [ ] B1. Riabilitazione funzionalità controller post-refactoring
- [ ] B2. Rimozione mapper (deprecato)
- [ ] B3. Refactor funzionalità controller
- [ ] B4. Rimozione DTO duplicato `MedicalServiceDTO`/`ServizioDTO`
- [ ] (... in aggiornamento)

**Comment by massimostanzione** [comment]
Segue come #413
