### ISSUE TITLE
Fetch festività da API esterne

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3#92]
Come configuratore vorrei che il sistema prelevasse le festività da un servizio esterno in autonomia così che non devo essere io ad aggiungerle

**Comment by msalvati1997** [comment]
Inserire la possibilità di chiamare l'API Rest del servizio esterno configurandone la località dell'applicazione.

Test di accettazione:
- Cambiando la variabile di località dell'applicazione verranno caricare festività diverse
